### ISSUE TITLE
Create an Event content type

### ISSUE THREAD

**Issue by carwin** [DrupalSGF/drupalsgf.org#5]
The Event content type should have the following fields for sure:
- Event name (alias of the title)
- Date (repeating / optional stuff / all day)
- Event description
- Event category (potentially taxonomy, but it could be more trouble than it's worth.)
  Here are my ideas:
  - Monthly meetup
  - Drinkup (21+)
  - Learn Sprint
  - Code Sprint
  - DrupalCamp
  - DrupalCon
  - Other - Con.
- Event location (I would prefer some way to integrate this with Google Maps).

**Comment by kweigand** [comment]
Event content type created - will be styled in design phase.

**Comment by carwin** [comment]
Merged into master.
