### ISSUE TITLE
Create DrupalSGF social media accounts

### ISSUE THREAD

**Issue by carwin** [DrupalSGF/drupalsgf.org#7]
Firstly - I think we need to set-up a Google Groups account, which I don't think is free anymore. However I think there's a way, if we sign up with Google App Engine to get it free anyway. The purpose here being group and site email accounts (info@drupalsgf.org), calendar, docs, Google+, etc... 

Other accounts will need to be managed by an email address within our domain so that if anyone leaves the group or moves away or something, we aren't reliant on them for access to that account.
- [x] Google Apps for Organizations
- [x] Twitter
- [x] Facebook
- [ ] ~~Google + (related to the first one)~~ (nevermind)

When you think of another one -- add it here.

**Comment by carwin** [comment]
I set up the Google Apps for Organizations account using the App Engine trick I mentioned. So we have a site email account and stuff. 

The only caveat is that we only get **1** user until we upgrade it. Oh well. I setup the DNS records for the domain and now info@drupalsgf.org can receive emails. Please let me know if you'd like to be added to the forward list for that.

Use that email to create all the other social accounts.

![Screen Shot 2013-01-12 at 6 24 21 PM](https://f.cloud.github.com/assets/715967/62460/b322ac20-5d17-11e2-8989-b73b92633526.png)

**Comment by carwin** [comment]
Twitter account created @DrupalSGF 

The login details can be found on a Google Drive document I started in the GApps account. Ping me for access.

**Comment by carwin** [comment]
Here is the embed code for our meetup calendar if we ever need it.

``` html
<iframe src="https://www.google.com/calendar/embed?title=Drupal%20SGF%20Meetups&amp;showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=300&amp;wkst=1&amp;hl=en&amp;bgcolor=%23ffffff&amp;src=info%40drupalsgf.org&amp;color=%232F6309&amp;ctz=America%2FChicago" style=" border-width:0 " width="300" height="300" frameborder="0" scrolling="no"></iframe>
```

**Comment by tarnus** [comment]
http://www.facebook.com/DrupalSGF  Added

**Comment by kweigand** [comment]
Added Logo and Header graphics. Made several initial posts. Confirmed posts are going to Twiiter Feed. Invited 242 friends. 16 have 'liked' the page.
